//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebsite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_MAS
    {
        public int CUSTID { get; set; }
        public string CUSTNAME { get; set; }
        public string CUSTADDRESS { get; set; }
        public string CUSTSTATUS { get; set; }
        public string CUSTEMAIL { get; set; }
        public string LINKTYPE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FILENAME { get; set; }
        public string FILETYPE { get; set; }
        public string FTPHOST { get; set; }
    }
}
