//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebsite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_PARA
    {
        public int CustId { get; set; }
        public string Supplier { get; set; }
        public string Shape { get; set; }
        public string Lab { get; set; }
        public string FromCTS { get; set; }
        public string ToCTS { get; set; }
        public string Color { get; set; }
        public string Clarity { get; set; }
        public string Cut { get; set; }
        public string Polish { get; set; }
        public string Symm { get; set; }
        public string Fls { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string Shade { get; set; }
        public string Luster { get; set; }
        public string Culet { get; set; }
        public string TableWhite { get; set; }
        public string CrownWhite { get; set; }
        public string TableBlack { get; set; }
        public string CrownBlack { get; set; }
        public string DiscBase { get; set; }
        public string Type { get; set; }
        public string Sign { get; set; }
        public string Value { get; set; }
    }
}
