//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebsite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCEL_DEMAND_DET
    {
        public int SEQ_NO { get; set; }
        public Nullable<int> MAS_SEQ { get; set; }
        public string DB_COLUMN { get; set; }
        public string EXCEL_COLUMN { get; set; }
        public Nullable<int> COLUMN_SEQ { get; set; }
        public string DISPLAY_NAME { get; set; }
    }
}
