//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebsite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURITY_MAS
    {
        public byte SEQ_NO { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public Nullable<byte> SORT_NO { get; set; }
        public string SYNONYM_LIST { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
