//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebsite.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradingDBEntities : DbContext
    {
        public TradingDBEntities()
            : base("name=TradingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COLOR_MAS> COLOR_MAS { get; set; }
        public virtual DbSet<CUT_MAS> CUT_MAS { get; set; }
        public virtual DbSet<EXCEL_DEMAND_DET> EXCEL_DEMAND_DET { get; set; }
        public virtual DbSet<FLS_MAS> FLS_MAS { get; set; }
        public virtual DbSet<LAB_MAS> LAB_MAS { get; set; }
        public virtual DbSet<POLISH_MAS> POLISH_MAS { get; set; }
        public virtual DbSet<PURITY_MAS> PURITY_MAS { get; set; }
        public virtual DbSet<SHAPE_MAS> SHAPE_MAS { get; set; }
        public virtual DbSet<SUPPLIER_MAS> SUPPLIER_MAS { get; set; }
        public virtual DbSet<SYMM_MAS> SYMM_MAS { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<CLIENT_STOCK> CLIENT_STOCK { get; set; }
        public virtual DbSet<COLUMN_MAS> COLUMN_MAS { get; set; }
        public virtual DbSet<FANCY_COLOR_MAS> FANCY_COLOR_MAS { get; set; }
        public virtual DbSet<EXCEL_DEMAND_MAS> EXCEL_DEMAND_MAS { get; set; }
        public virtual DbSet<CUSTOMER_MAS> CUSTOMER_MAS { get; set; }
        public virtual DbSet<CUSTOMER_PARA> CUSTOMER_PARA { get; set; }
    }
}
